#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check --path ./bundle 2>&1 > /dev/null || {
  bundle install --path ./bundle --binstubs ./bundle/bin --quiet --without production
}

bundle/bin/overcommit 2>&1 > /dev/null
